Storage
AY2021S2-CS2113T-W09-3/tp pull request #11
Opened 2021-03-04 06:20 UTC by 8kdesign

Split storage into two parts: Loader and Writer.
Interact with them through methods in ModuleList:
1) Use addModule to create a new module.
2) Use removeModule to delete a module.
3) Use setSelectedModule to select a module. Returns false if not found.
4) Use reset to set selected module to null.

2021-03-04 09:05 UTC, isaharon requested changes

2021-03-04 09:05 UTC, isaharon commented on src/main/java/seedu/duke/lesson/Lesson.java
> +    private String onlineLink = "";
Consider creating a default constructor

2021-03-04 09:05 UTC, isaharon commented on src/main/java/seedu/duke/lesson/TeachingStaff.java
> +    private final String name;
Remove final

2021-03-04 09:05 UTC, isaharon commented on src/main/java/seedu/duke/module/ModuleList.java
> +    private static final Writer writer = new Writer();
To remove from object class

2021-03-04 09:05 UTC, isaharon commented on src/main/java/seedu/duke/storage/Loader.java
> +                ModuleList.addModule(name.replace(Constants.FILE_FORMAT, ""));
addModule creates new file after loading?

2021-03-04 09:05 UTC, isaharon commented on src/main/java/seedu/duke/task/Task.java
> +    private String remarks = "";
Consider creating a default constructor

2021-03-04 14:06 UTC, isaharon reviewed
LGTM!

2021-03-08 09:21 UTC, isaharon approved these changes

2021-03-08 13:18 UTC, ivanchongzhien requested changes
Mostly went through the code for Writer and Loader, skipped your tests. LGTM except maybe change the way you import constants?

2021-03-08 13:18 UTC, ivanchongzhien commented on src/main/java/seedu/duke/storage/Loader.java
> +import seedu.duke.common.Constants;
Consider replacing this line with:

import static seedu.duke.common.Constants.(constant name)

so you don't have to repeatedly use Constants.(constant name)? I think if you are using most of the constants in that class, it is acceptable to use *.

2021-03-08 13:18 UTC, ivanchongzhien commented on src/main/java/seedu/duke/storage/Writer.java
> +import seedu.duke.common.Constants;
Same as Loader class, consider import static?

2021-03-08 23:07 UTC, 8kdesign commented on src/main/java/seedu/duke/common/Constants.java
> +public class Constants {
Hmm. But some will overlap, like the index of the fields. We should try to merge them.

2021-03-09 13:39 UTC, ivanchongzhien approved these changes
LGTM

2021-03-09 13:52 UTC, merged